#config_version=6
#attract mode config file


slide_player:
  mode_attract_started: joe_ros_intro

  mode_attract_stopping:
    joe_ros_intro:
      action: remove

show_player:
    mode_attract_started:
      blinking_start:
        loops: -1
        
event_player:
  s_start_active: shake_shake_shake
  
