#config_version=6
#attract mode config file

slide_player:
  mode_attract_started: joe_ros_intro

  mode_attract_stopping:
    joe_ros_intro:
      action: remove

show_player:
    mode_attract_started:
      blinking_start:
        loops: -1
        
coil_player:
  s_lower_left_flipper_active: 
    dwc_storm_shadow:
      action: enable
          
event_player:
  s_lower_left_flipper_active: blower_low
  s_lower_right_flipper_active: blower_off
