#config_version=6
#simple mode to show mode transitions

mode:
    start_events: start_mode_1
    stop_events: stop_mode_1
    priority: 200
    
shot_profiles:       
  red_flashing_lit_profile:
    states:
      - name: flashing
        show: red_flashing
      - name: lit
        show: red_solid

shots:
  #Pop shots - will be flashing until hit, once hit, will be lit and remain lit
  m1_pop_1_shot:
    switch: s_pop_bumper_cc_1
    profile: red_flashing_lit_profile
    show_tokens: { light: l_pop_1 }
  m1_pop_2_shot:
    switch: s_pop_bumper_cc_2
    profile: red_flashing_lit_profile
    show_tokens: { light: l_pop_2 }
  m1_pop_3_shot:
    switch: s_pop_bumper_cc_3
    profile: red_flashing_lit_profile
    show_tokens: { light: l_pop_3 }
    
  #Lane shots - will be flashing until hit, once hit, will be lit and remain lit
  m1_left_outlane_shot:
    switch: s_left_outlane
    profile: red_flashing_lit_profile
    show_tokens: { light: l_left_outlane }
  m1_left_inlane_shot:
    switch: s_left_inlane
    profile: red_flashing_lit_profile
    show_tokens: { light: l_left_inlane }
  m1_right_inlane_shot:
    switch: s_right_inlane
    profile: red_flashing_lit_profile
    show_tokens: { light: l_right_inlane }
  m1_right_outlane_shot:
    switch: s_right_outlane
    profile: red_flashing_lit_profile
    show_tokens: { light: l_right_outlane }
    
shot_groups:
  m1_pops_shot_group:
    shots: m1_pop_1_shot, m1_pop_2_shot, m1_pop_3_shot
  m1_lanes_shot_group:
    shots: m1_left_outlane_shot, m1_left_inlane_shot, m1_right_inlane_shot, m1_right_outlane_shot

event_player:
  m1_pops_shot_group_lit_complete: stop_mode_1
  m1_lanes_shot_group_lit_complete: stop_mode_1
  
