#config_version=6

coils:
  #=====================
  # Cabinet IO Coils
  #=====================
  # Cabinet IO Coin Door - J4
  #---------------------
  c_left_coin_driver:
    number: cabinet-0
    allow_enable: true
    console_log: none
    file_log: none
  c_right_coin_driver:
    number: cabinet-1
    allow_enable: true
    console_log: none
    file_log: none
  #---------------------
  # Cabinet IO Left - J1
  #---------------------
  #unused:
    #number: cabinet-2
  c_start_driver:
    number: cabinet-3
    allow_enable: true
    console_log: none
    file_log: none
  #---------------------
  # Cabinet IO Right - J9
  #---------------------
  #unused:
    #number: cabinet-4
    #number: cabinet-5
    
  #=====================
  # Playfield IO 3208 Coils
  #=====================
  # J4 - Drivers 0-7
  #---------------------
  c_trough_eject:
    number: playfield-0
    default_pulse_ms: 12
  c_auto_kicker:
    number: playfield-1
    default_pulse_ms: 18
  c_left_sling:
    number: playfield-2
    default_pulse_ms: 15
  c_right_sling:
    number: playfield-3
    default_pulse_ms: 15
  c_lower_left_flipper_main:
    number: playfield-4
    default_pulse_ms: 25
  c_lower_left_flipper_hold:
    number: playfield-5
    default_hold_power: .5
  c_lower_right_flipper_main:
    number: playfield-6
    default_pulse_ms: 25
  c_lower_right_flipper_hold:
    number: playfield-7
    default_hold_power: .5

autofire_coils:
  #=====================  
  # Slingshots
  #=====================
  afc_right_sling:
    coil: c_right_sling
    switch: s_sling_left
    
  afc_left_sling:
    coil: c_left_sling
    switch: s_sling_left
