#config_version=6

coils:
  #=====================
  # Cabinet IO Coils
  #=====================
  # Cabinet IO Coin Door - J4
  #---------------------
  c_left_coin_driver:
    number: cabinet-0
    allow_enable: true
    console_log: none
    file_log: none
  c_right_coin_driver:
    number: cabinet-1
    allow_enable: true
    console_log: none
    file_log: none
  #---------------------
  # Cabinet IO Left - J1
  #---------------------
  #unused:
    #number: cabinet-2
  c_start_driver:
    number: cabinet-3
    allow_enable: true
    console_log: none
    file_log: none
  #---------------------
  # Cabinet IO Knocker - J2
  #---------------------  
  c_blower_fan:
    number: cabinet-7 # D1 - note in FAST docs says to use 7
    allow_enable: true
    default_hold_power: 0.3  # Default to Low speed (30% power)
  #---------------------
  # Cabinet IO Right - J9
  #---------------------
  #unused:
    #number: cabinet-4
    #number: cabinet-5
    
  #=====================
  # Playfield IO 3208 Coils
  #=====================
  # J4 - Drivers 0-7
  #---------------------
  c_trough_eject:
    number: playfield-0
    default_pulse_ms: 12
  c_auto_kicker:
    number: playfield-1
    default_pulse_ms: 18
  c_left_sling:
    number: playfield-2
    default_pulse_ms: 15
  c_right_sling:
    number: playfield-3
    default_pulse_ms: 15
  c_lower_left_flipper_main:
    number: playfield-4
    default_pulse_ms: 25
  c_lower_left_flipper_hold:
    number: playfield-5
    default_hold_power: .5
  c_lower_right_flipper_main:
    number: playfield-6
    default_pulse_ms: 25
  c_lower_right_flipper_hold:
    number: playfield-7
    default_hold_power: .5
    
  #=====================
  # Playfield IO 1616 Coils
  #=====================
  # J3 - Drivers 0-7
  #---------------------
  c_upper_left_flipper_main:
    number: upper_playfield-0
    default_pulse_ms: 25
  c_upper_left_flipper_hold:
    number: upper_playfield-1
    default_hold_power: .5
  c_upper_right_flipper_main:
    number: upper_playfield-2
    default_pulse_ms: 25
  c_upper_right_flipper_hold:
    number: upper_playfield-3
    default_hold_power: .5
  c_storm_shadow_main:
    number: upper_playfield-4
    default_pulse_ms: 25
  c_storm_shadow_hold:
    number: upper_playfield-5
    default_hold_power: .5
  c_snake_eyes_main:
    number: upper_playfield-6
    default_pulse_ms: 25
  c_snake_eyes_hold:
    number: upper_playfield-7
    default_hold_power: .5
  #---------------------
  # J4 - Drivers 8-15
  #---------------------
  c_left_mass_vuk:
    number: upper_playfield-8
    default_pulse_ms: 25
  c_right_mass_vuk:
    number: upper_playfield-9
    default_pulse_ms: 25
  #unused:
    #number: upper_playfield-10
    #number: upper_playfield-11
    #number: upper_playfield-12
    #number: upper_playfield-13
    #number: upper_playfield-14
    #number: upper_playfield-15
    
dual_wound_coils:
  dwc_storm_shadow:
    hold_coil: c_storm_shadow_hold
    main_coil: c_storm_shadow_main
    eos_switch: s_storm_shadow_eos
  dwc_snake_eyes:
    hold_coil: c_snake_eyes_hold
    main_coil: c_snake_eyes_main
    eos_switch: s_snake_eyes_eos
    
    
autofire_coils:
  #=====================  
  # Slingshots
  #=====================
  afc_right_sling:
    coil: c_right_sling
    switch: s_sling_right
    
  afc_left_sling:
    coil: c_left_sling
    switch: s_sling_left
