#config_version=6

mpf:
  report_crashes: never

hardware:
    platform: fast

fast:
  net:
    controller: neuron
    port: auto
    io_loop:
      cabinet:
        model: FP-I/O-0024
        order: 1
      playfield:
        model: FP-I/O-3208
        order: 2
      upper_playfield:
        model: FP-I/O-1616
        order: 3

  exp:
    debug: true
    port: auto
    boards:
      shakerboard:
        model: FP-EXP-1313
      neuron:
        model: FP-EXP-2000


#Window is your total size for your displays, below is setup for use with one 1080p monitor.

#window:
#  width: 1920
#  height: 1080
#  title: MPF All Display Window
#  fullscreen: false
#  resizable: true
#  borderless: true
#  exit_on_escape: true
#  no_window: false
#  show_cursor: no


displays:
  window:
    width: 1920
    height: 1080
  display1:
    width: 1920
    height: 1080

playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

machine:
    balls_installed: 1

game:
    balls_per_game: 3
    max_players: 1
    
#=============================
# Config Files
#=============================
config:
  - ball_devices.yaml
  - blower.yaml
  - coils.yaml
  - flippers.yaml
  - lights.yaml
  - modes.yaml
  - player_variables.yaml
  - sequence_shots.yaml
  - shakers.yaml
  - spinners.yaml
  - switches_cabinet.yaml
  - switches_upper_playfield.yaml
  - switches_playfield.yaml
  - variables.yaml

virtual_platform_start_active_switches:
  - s_trough_ball_1
  - s_trough_ball_2
  - s_trough_ball_3
  - s_trough_ball_4
  - s_trough_ball_5
  - s_trough_ball_6
  - s_trough_ball_7
  - s_trough_ball_8
