#config_version=6

hardware:
    platform: fast

fast:
  net:
    controller: neuron
    port: auto
    io_loop:
      cabinet:
        model: FP-I/O-0024
        order: 1
      playfield:
        model: FP-I/O-3208
        order: 2

  exp:
    debug: true
    port: auto
    boards:
      shakerboard:
        model: FP-EXP-1313
      neuron:
        model: FP-EXP-2000


#Window is your total size for your displays, below is setup for use with one 1080p monitor.

#window:
#  width: 1920
#  height: 1080
#  title: MPF All Display Window
#  fullscreen: false
#  resizable: true
#  borderless: true
#  exit_on_escape: true
#  no_window: false
#  show_cursor: no


displays:
  window:
    width: 1920
    height: 1080
  display1:
    width: 1920
    height: 1080





playfields:
  playfield:
    default_source_device: bd_plunger
    tags: default

machine:
    balls_installed: 8

game:
    balls_per_game: 1
    max_players: 1
    
#=============================
# Config Files
#=============================
config:
  - lights.yaml
  - coils.yaml
  - switches.yaml
  - variables.yaml

#=============================
# Modes
#=============================
modes:
  #- base
  - attract
  #- char_select
  #- mode_1

#=============================
# Flippers
#=============================
flippers:
  flipper_lower_left:
    main_coil: c_lower_left_flipper_main
    hold_coil: c_lower_left_flipper_hold
    activation_switch: s_lower_left_flipper
    eos_switch: s_lower_left_flipper_eos
    enable_events: ball_started
    disable_events: ball_will_end, service_mode_entered
  #right_flipper:
    #main_coil: c_flipper_right_full
    #hold_coil: c_flipper_right_hold
    #eos_switch: s_flipper_right_eos
    #activation_switch: s_flipper_right
    #enable_events: ball_started, machine_reset_phase_3 # TODO, remove from game
    #disable_events: ball_will_end, service_mode_entered, disableAutofire    
    
  #left_flipper_upper:
    #main_coil: c_flipper_left_upper_full
    #hold_coil: c_flipper_left_upper_hold
    #activation_switch: s_flipper_left
    #eos_switch: s_flipper_left_upper_eos
    #enable_events: ball_started, enableAutofire, machine_reset_phase_3 # TODO, remove from game
    #disable_events: ball_will_end, service_mode_entered, disableAutofire
      
#=============================
# Ball Devices
#=============================      
ball_devices:

  bd_trough:
    ball_switches: s_trough_ball_1, s_trough_ball_2, s_trough_ball_3, s_trough_ball_4, s_trough_ball_5, s_trough_ball_6, s_trough_ball_7, s_trough_ball_8
    tags: trough, home, drain
    eject_coil: c_trough_eject
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 2s
    max_eject_attempts: 3

  bd_plunger:
    ball_switches: s_plunger
    eject_coil: c_auto_kicker
    mechanical_eject: true
    eject_timeouts: 5s

virtual_platform_start_active_switches:
  - s_trough_ball_1
  - s_trough_ball_2
  - s_trough_ball_3
  - s_trough_ball_4
  - s_trough_ball_5
  - s_trough_ball_6
  - s_trough_ball_7
  - s_trough_ball_8

#=============================
# Shakers
#=============================  
shakers:
  main_shaker:
    number: shakerboard-1
    debug: true
    default_power: 0.5
    control_events:
      shake_shake_shake:
        power: 0.5
        duration: 3s      
