#config_version=6

hardware:
    platform: fast


fast:
  net:
    controller: neuron
    port: auto
    io_loop:
      cabinet_io:
        model: FP-I/O-0024
        order: 1
      playfield_io:
        model: FP-I/O-3208
        order: 2

  exp:
    debug: true
    port: auto
    boards:
      shakerboard:
        model: FP-EXP-1313
      neuron:
        model: FP-EXP-2000


#Window is your total size for your displays, below is setup for use with one 1080p monitor.

#window:
#  width: 1920
#  height: 1080
#  title: MPF All Display Window
#  fullscreen: false
#  resizable: true
#  borderless: true
#  exit_on_escape: true
#  no_window: false
#  show_cursor: no


displays:

  window:
    width: 1920
    height: 1080
  display1:
    width: 1920
    height: 1080



#slides:
 # slide_layout:
 #   target: window
 #   background_color: white #white for test
 #   widgets:
 #     - type: display
 #       source_display: display1
 #       width: 1920
 #       height: 1080
 #       x: right
 #       anchor_x: right


#slide_player:
#  mc_ready:
#    slide_layout:
#      target: window

#Game Config

config:
  - lights.yaml
  - coils.yaml
  - switches.yaml
  - variables.yaml


playfields:
  #Define your playfields

  playfield:
    default_source_device: bd_plunger
    tags: default

machine:
    balls_installed: 6

game:
    balls_per_game: 1
    max_players: 1

modes:
  - base
  - attract
  - char_select
  - mode_1

#Flippers
flippers:
  left_flipper_lower:
    main_coil: c_flipper_left_lower_full
    hold_coil: c_flipper_left_lower_hold
    activation_switch: s_flipper_left
    eos_switch: s_flipper_left_lower_eos
    enable_events: ball_started, enableAutofire, machine_reset_phase_3 # TODO, remove from game
    disable_events: ball_will_end, service_mode_entered, disableAutofire
  left_flipper_upper:
    main_coil: c_flipper_left_upper_full
    hold_coil: c_flipper_left_upper_hold
    activation_switch: s_flipper_left
    eos_switch: s_flipper_left_upper_eos
    enable_events: ball_started, enableAutofire, machine_reset_phase_3 # TODO, remove from game
    disable_events: ball_will_end, service_mode_entered, disableAutofire

  right_flipper:
    main_coil: c_flipper_right_full
    hold_coil: c_flipper_right_hold
    eos_switch: s_flipper_right_eos
    activation_switch: s_flipper_right
    enable_events: ball_started, enableAutofire, machine_reset_phase_3 # TODO, remove from game
    disable_events: ball_will_end, service_mode_entered, disableAutofire

      
ball_devices:

  bd_trough:

    ball_switches: s_trough_ball_1, s_trough_ball_2, s_trough_ball_3, s_trough_ball_4, s_trough_ball_5, s_trough_ball_6
    #mechanical_eject: true
    tags: trough, home, drain
    eject_coil: c_trough_eject_coil
    eject_coil_jam_pulse: 15ms
    eject_targets: bd_plunger
    eject_timeouts: 2s
    max_eject_attempts: 1

  bd_plunger:
    ball_switches: s_plunger
    mechanical_eject: true
    eject_timeouts: 5s

#Example Drop Target Bank setup. This can be setup how you need it

#drop_targets:
#    lowerDrop1_target:
#         switch: s_lowerDrop1
#    lowerDrop2_target:
#         switch: s_lowerDrop2
virtual_platform_start_active_switches:
  - s_trough_ball_1
  - s_trough_ball_2
  - s_trough_ball_3
  - s_trough_ball_4
  - s_trough_ball_5
  - s_trough_ball_6


drop_target_banks:

#    TEAM_bank:
#        drop_targets: lowerDrop1_target, lowerDrop2_target
#        reset_coil: c_reset_4bank
#        reset_coil_max_wait_ms: 150
#        reset_events:
#           machine_reset_phase_3: 100ms
#           ball_starting: 100ms

shakers:
  main_shaker:
    number: shakerboard-1
    debug: true
    default_power: 0.5
    control_events:
      shake_shake_shake:
        power: 0.05
        duration: 1s      
