#config_version=6

lights:
  #=============================
  # Cabinet IO Lights
  #=============================
  # Cabinet IO Left - J1
  #-----------------------------
  l_start:
    number: c_start_driver
    platform: drivers
    type: r
  #-----------------------------
  # Cabinet Coin Door - J4
  #-----------------------------
  l_left_coin:
    number: c_left_coin_driver
    platform: drivers
    type: r
  l_right_coin:
    number: c_right_coin_driver
    platform: drivers
    type: r
