#config_version=6

lights:
  #=============================
  # Cabinet IO Lights
  #=============================
  # Cabinet IO Left - J1
  #-----------------------------
  l_start:
    number: c_start_driver
    platform: drivers
    type: r
  #-----------------------------
  # Cabinet Coin Door - J4
  #-----------------------------
  l_left_coin:
    number: c_left_coin_driver
    platform: drivers
    type: r
  l_right_coin:
    number: c_right_coin_driver
    platform: drivers
    type: r
    
  # l_left_mass_red_crystals:
  #   number: 1
  #   tags: l_red_crystals
  # l_left_mass_heavy_water:
  #   number: 2
  #   tags: l_heavy_water
  # l_left_mass_meteor_dust:
  #   number: 3
  #   tags: l_meteor_dust
    
  # l_right_mass_red_crystals:
  #   number: 4
  #   tags: l_red_crystals
  # l_right_mass_heavy_water:
  #   number: 5
  #   tags: l_heavy_water
  # l_right_mass_meteor_dust:
  #   number: 6
  #   tags: l_meteor_dust
    
  # l_cube_top_left_1:
  #   number: 1-1
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_2:
  #   number: 1-2
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_3:
  #   number: 1-3
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_4:
  #   number: 1-4
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_5:
  #   number: 1-5
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_6:
  #   number: 1-6
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_7:
  #   number: 1-7
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_8:
  #   number: 1-8
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_9:
  #   number: 1-9
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_10:
  #   number: 1-10
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_11:
  #   number: 1-11
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_12:
  #   number: 1-12
  #   tags: l_cube_top_left, l_cubes
    
  # l_cube_top_right_1:
  #   number: 2-1
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_2:
  #   number: 2-2
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_3:
  #   number: 2-3
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_4:
  #   number: 2-4
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_5:
  #   number: 2-5
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_6:
  #   number: 2-6
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_7:
  #   number: 2-7
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_8:
  #   number: 2-8
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_9:
  #   number: 2-9
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_10:
  #   number: 2-10
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_11:
  #   number: 2-11
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_12:
  #   number: 2-12
  #   tags: l_cube_top_right, l_cubes
    
  # l_cube_bottom_left_1:
  #   number: 3-1
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_2:
  #   number: 3-2
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_3:
  #   number: 3-3
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_4:
  #   number: 3-4
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_5:
  #   number: 3-5
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_6:
  #   number: 3-6
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_7:
  #   number: 3-7
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_8:
  #   number: 3-8
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_9:
  #   number: 3-9
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_10:
  #   number: 3-10
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_11:
  #   number: 3-11
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_12:
  #   number: 3-12
  #   tags: l_cube_bottom_left, l_cubes
    
  # l_cube_bottom_right_1:
  #   number: 4-1
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_2:
  #   number: 4-2
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_3:
  #   number: 4-3
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_4:
  #   number: 4-4
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_5:
  #   number: 4-5
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_6:
  #   number: 4-6
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_7:
  #   number: 4-7
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_8:
  #   number: 4-8
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_9:
  #   number: 4-9
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_10:
  #   number: 4-10
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_11:
  #   number: 4-11
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_12:
  #   number: 4-12
  #   tags: l_cube_bottom_right, l_cubes
