#config_version=6

lights:
#=============================
# Cabinet IO Lights
#=============================
# Cabinet IO Left - J1
#-----------------------------
  l_start:
    number: c_start_driver
    platform: drivers
    type: r
#-----------------------------
# Cabinet Coin Door - J4
#-----------------------------
  l_left_coin:
    number: c_left_coin_driver
    platform: drivers
    type: r
  l_right_coin:
    number: c_right_coin_driver
    platform: drivers
    type: r

#=============================
# Neuron Lights
#=============================
# Neuron Lights - Port 1 - allocation updated to 64 in config
#-----------------------------
  l_left_rail_1:
    number: neuron-1-1
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_2:
    number: neuron-1-2
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_3:
    number: neuron-1-3
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_4:
    number: neuron-1-4
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_5:
    number: neuron-1-5
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_6:
    number: neuron-1-6
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_7:
    number: neuron-1-7
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_8:
    number: neuron-1-8
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_9:
    number: neuron-1-9
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_10:
    number: neuron-1-10
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_11:
    number: neuron-1-11
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_12:
    number: neuron-1-12
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_13:
    number: neuron-1-13
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_14:
    number: neuron-1-14
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_15:
    number: neuron-1-15
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_16:
    number: neuron-1-16
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_17:
    number: neuron-1-17
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_18:
    number: neuron-1-18
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_19:
    number: neuron-1-19
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_20:
    number: neuron-1-20
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_21:
    number: neuron-1-21
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_22:
    number: neuron-1-22
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_23:
    number: neuron-1-23
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_24:
    number: neuron-1-24
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_25:
    number: neuron-1-25
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_26:
    number: neuron-1-26
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_27:
    number: neuron-1-27
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_28:
    number: neuron-1-28
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_29:
    number: neuron-1-29
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_30:
    number: neuron-1-30
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_31:
    number: neuron-1-31
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_32:
    number: neuron-1-32
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_33:
    number: neuron-1-33
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_34:
    number: neuron-1-34
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_35:
    number: neuron-1-35
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_36:
    number: neuron-1-36
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_37:
    number: neuron-1-37
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_38:
    number: neuron-1-38
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_39:
    number: neuron-1-39
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_40:
    number: neuron-1-40
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_41:
    number: neuron-1-41
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_42:
    number: neuron-1-42
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_43:
    number: neuron-1-43
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_44:
    number: neuron-1-44
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_45:
    number: neuron-1-45
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_46:
    number: neuron-1-46
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_47:
    number: neuron-1-47
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_48:
    number: neuron-1-48
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_49:
    number: neuron-1-49
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_50:
    number: neuron-1-50
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_51:
    number: neuron-1-51
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_52:
    number: neuron-1-52
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_53:
    number: neuron-1-53
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_54:
    number: neuron-1-54
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_55:
    number: neuron-1-55
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_56:
    number: neuron-1-56
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_57:
    number: neuron-1-57
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_58:
    number: neuron-1-58
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_59:
    number: neuron-1-59
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_60:
    number: neuron-1-60
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_61:
    number: neuron-1-61
    tags: l_left_rail, l_rails, group_a, left_group_a
  l_left_rail_62:
    number: neuron-1-62
    tags: l_left_rail, l_rails, group_b, left_group_b
  l_left_rail_63:
    number: neuron-1-63
    tags: l_left_rail, l_rails, group_c, left_group_c
  l_left_rail_64:
    number: neuron-1-64
    tags: l_left_rail, l_rails, group_a, left_group_a
  
#-----------------------------
# Neuron Lights - Port 2 - allocation updated to 64 in config
#-----------------------------
  l_right_rail_1:
    number: neuron-2-1
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_2:
    number: neuron-2-2
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_3:
    number: neuron-2-3
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_4:
    number: neuron-2-4
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_5:
    number: neuron-2-5
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_6:
    number: neuron-2-6
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_7:
    number: neuron-2-7
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_8:
    number: neuron-2-8
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_9:
    number: neuron-2-9
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_10:
    number: neuron-2-10
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_11:
    number: neuron-2-11
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_12:
    number: neuron-2-12
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_13:
    number: neuron-2-13
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_14:
    number: neuron-2-14
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_15:
    number: neuron-2-15
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_16:
    number: neuron-2-16
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_17:
    number: neuron-2-17
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_18:
    number: neuron-2-18
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_19:
    number: neuron-2-19
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_20:
    number: neuron-2-20
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_21:
    number: neuron-2-21
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_22:
    number: neuron-2-22
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_23:
    number: neuron-2-23
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_24:
    number: neuron-2-24
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_25:
    number: neuron-2-25
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_26:
    number: neuron-2-26
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_27:
    number: neuron-2-27
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_28:
    number: neuron-2-28
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_29:
    number: neuron-2-29
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_30:
    number: neuron-2-30
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_31:
    number: neuron-2-31
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_32:
    number: neuron-2-32
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_33:
    number: neuron-2-33
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_34:
    number: neuron-2-34
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_35:
    number: neuron-2-35
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_36:
    number: neuron-2-36
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_37:
    number: neuron-2-37
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_38:
    number: neuron-2-38
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_39:
    number: neuron-2-39
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_40:
    number: neuron-2-40
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_41:
    number: neuron-2-41
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_42:
    number: neuron-2-42
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_43:
    number: neuron-2-43
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_44:
    number: neuron-2-44
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_45:
    number: neuron-2-45
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_46:
    number: neuron-2-46
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_47:
    number: neuron-2-47
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_48:
    number: neuron-2-48
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_49:
    number: neuron-2-49
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_50:
    number: neuron-2-50
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_51:
    number: neuron-2-51
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_52:
    number: neuron-2-52
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_53:
    number: neuron-2-53
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_54:
    number: neuron-2-54
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_55:
    number: neuron-2-55
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_56:
    number: neuron-2-56
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_57:
    number: neuron-2-57
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_58:
    number: neuron-2-58
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_59:
    number: neuron-2-59
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_60:
    number: neuron-2-60
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_61:
    number: neuron-2-61
    tags: l_right_rail, l_rails, group_a, right_group_a
  l_right_rail_62:
    number: neuron-2-62
    tags: l_right_rail, l_rails, group_b, right_group_b
  l_right_rail_63:
    number: neuron-2-63
    tags: l_right_rail, l_rails, group_c, right_group_c
  l_right_rail_64:
    number: neuron-2-64
    tags: l_right_rail, l_rails, group_a, right_group_a
    
  #-----------------------------
  # Neuron Lights - Port 3 - allocation updated to 0 in config
  #----------------------------- 
  # Neuron Lights - Port 4 - allocation updated to 0 in config
  #----------------------------- 
    
  # l_left_mass_red_crystals:
  #   number: 1
  #   tags: l_red_crystals
  # l_left_mass_heavy_water:
  #   number: 2
  #   tags: l_heavy_water
  # l_left_mass_meteor_dust:
  #   number: 3
  #   tags: l_meteor_dust
    
  # l_right_mass_red_crystals:
  #   number: 4
  #   tags: l_red_crystals
  # l_right_mass_heavy_water:
  #   number: 5
  #   tags: l_heavy_water
  # l_right_mass_meteor_dust:
  #   number: 6
  #   tags: l_meteor_dust
    
  # l_cube_top_left_1:
  #   number: 1-1
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_2:
  #   number: 1-2
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_3:
  #   number: 1-3
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_4:
  #   number: 1-4
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_5:
  #   number: 1-5
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_6:
  #   number: 1-6
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_7:
  #   number: 1-7
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_8:
  #   number: 1-8
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_9:
  #   number: 1-9
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_10:
  #   number: 1-10
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_11:
  #   number: 1-11
  #   tags: l_cube_top_left, l_cubes
  # l_cube_top_left_12:
  #   number: 1-12
  #   tags: l_cube_top_left, l_cubes
    
  # l_cube_top_right_1:
  #   number: 2-1
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_2:
  #   number: 2-2
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_3:
  #   number: 2-3
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_4:
  #   number: 2-4
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_5:
  #   number: 2-5
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_6:
  #   number: 2-6
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_7:
  #   number: 2-7
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_8:
  #   number: 2-8
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_9:
  #   number: 2-9
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_10:
  #   number: 2-10
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_11:
  #   number: 2-11
  #   tags: l_cube_top_right, l_cubes
  # l_cube_top_right_12:
  #   number: 2-12
  #   tags: l_cube_top_right, l_cubes
    
  # l_cube_bottom_left_1:
  #   number: 3-1
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_2:
  #   number: 3-2
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_3:
  #   number: 3-3
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_4:
  #   number: 3-4
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_5:
  #   number: 3-5
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_6:
  #   number: 3-6
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_7:
  #   number: 3-7
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_8:
  #   number: 3-8
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_9:
  #   number: 3-9
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_10:
  #   number: 3-10
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_11:
  #   number: 3-11
  #   tags: l_cube_bottom_left, l_cubes
  # l_cube_bottom_left_12:
  #   number: 3-12
  #   tags: l_cube_bottom_left, l_cubes
    
  # l_cube_bottom_right_1:
  #   number: 4-1
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_2:
  #   number: 4-2
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_3:
  #   number: 4-3
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_4:
  #   number: 4-4
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_5:
  #   number: 4-5
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_6:
  #   number: 4-6
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_7:
  #   number: 4-7
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_8:
  #   number: 4-8
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_9:
  #   number: 4-9
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_10:
  #   number: 4-10
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_11:
  #   number: 4-11
  #   tags: l_cube_bottom_right, l_cubes
  # l_cube_bottom_right_12:
  #   number: 4-12
  #   tags: l_cube_bottom_right, l_cubes
