#config_version=6

switches:
  #=============================
  # Cabinet IO Switches
  # - 24 switch inputs, 8 driver outputs
  # - 1 high power driver
  # - 6 low current drivers for LEDs
  # - 2 digital outputs (bill validator and card readers)
  #=============================
  # Cabinet Coin Door
  #-----------------------------
  s_coin_1:
    number: cabinet-0
    tags: coin, s_left_coin
  s_coin_2:
    number: cabinet-1
    tags: coin, s_right_coin
  s_service_esc:
    number: cabinet-2
    tags: exit
  s_service_down:
    number: cabinet-3
    tags: down
  s_service_up:
    number: cabinet-4
    tags: up
  s_service_enter:
    number: cabinet-5
    tags: enter
  #unused:
    #number: cabinet-6
    #number: cabinet-7
  #-----------------------------
  # Cabinet IO Left
  #-----------------------------
  s_start:
    number: cabinet-8
    tags: start
  s_lower_left_flipper:
    number: cabinet-9
    tags: left_flipper
    debounce: normal
  s_upper_left_flipper:
    number: cabinet-10
    debounce: normal
  s_tilt:
    number: cabinet-11
    debounce: normal
  #unused:
    #number: cabinet-12
    #number: cabinet-13
    #number: cabinet-14
    #number: cabinet-15
  #-----------------------------
  # Cabinet IO Right
  #-----------------------------
  s_lower_right_flipper:
    number: cabinet-16
    tags: right_flipper
    debounce: normal
  s_upper_right_flipper:
    number: cabinet-17
    debounce: normal
  #unused:    
    #number: cabinet-18
    #number: cabinet-19
    #number: cabinet-20
    #number: cabinet-21
    #number: cabinet-22
    #number: cabinet-23
  #-----------------------------
  # Bill/Card/Ticket - UNUSED SHARES PINS W/ Cabinet IO Right
  #-----------------------------

 
  #=============================
  # Playfield IO 3208 Switches
  # - 32 switch inputs, 8 driver outputs
  #=============================
  # J8 - Switch Bank 0-7
  #-----------------------------

  s_trough_ball_1: #opto
    number: playfield-0
    type: 'NC'
  s_trough_ball_2:
    number: playfield-1
  s_trough_ball_3:
    number: playfield-2
  s_trough_ball_4:
    number: playfield-3
  s_trough_ball_5:
    number: playfield-4
  s_trough_ball_6:
    number: playfield-5
  s_trough_ball_7:
    number: playfield-6
  s_trough_ball_8:
    number: playfield-7
  #-----------------------------
  # J3 - Switch Bank 8-15
  #-----------------------------
  s_trough_ball_jam: #opto
    number: playfield-8
    type: 'NC'
  s_sling_left:
    number: playfield-9
  s_sling_right:
    number: playfield-10
  s_lower_left_flipper_eos:
    number: playfield-11
  s_lower_right_flipper_eos:
    number: playfield-12
  s_plunger:
    number: playfield-13
  s_left_inlane:
    number: playfield-14
  s_left_outlane:
    number: playfield-15
  #-----------------------------
    # J6 - Switch Bank 16-23
  #-----------------------------
  #unused:
    #number: playfield-16
    #number: playfield-17
    #number: playfield-18
    #number: playfield-19
    #number: playfield-20
    #number: playfield-21
    #number: playfield-22
    #number: playfield-23
  #-----------------------------
  # J9 - Switch Bank 24-31
  #-----------------------------
  s_right_inlane:
    number: playfield-24
  s_right_outlane:    
    number: playfield-25
  s_storm_shadow_eos: #pop up mech eos switch
    number: playfield-26
  s_storm_shadow: #storm shadow ninja head switch
    number: playfield-27  
  #unused:    
    #number: playfield-28
    #number: playfield-29
    #number: playfield-30
    #number: playfield-31
    
  #s_left_mass_vuk_1:
  #  number: 1
  #s_left_mass_vuk_2:
  #  number: 2
  #s_left_mass_vuk_3:
  #  number: 3
  #s_left_mass_entrance:
  #  number: 4
    
  #s_right_mass_vuk_1:
  #  number: 5
  #s_right_mass_vuk_2:
  #  number: 6
  #s_right_mass_vuk_3:
  #  number: 7
  #s_right_mass_entrance:
  #  number: 8
 
  #=============================
  # Playfield IO 1616 Switches
  # - 16 switch inputs, 16 driver outputs
  #=============================
  # J7 - Switch Bank 0-7
  #-----------------------------
  s_left_ninja:
    number: upper_playfield-0
  s_right_ninja:
    number: upper_playfield-1
  #unused:    
    #number: upper_playfield-2
    #number: upper_playfield-3
  s_snake_eyes_eos:
    number: upper_playfield-4
  s_snake_eyes:
    number: upper_playfield-5
  s_heavy_water:
    number: upper_playfield-6
  s_left_ramp:
    number: upper_playfield-7
  #-----------------------------
  # J8 - Switch Bank 8-15
  #-----------------------------
  s_left_orbit:
    number: upper_playfield-8
  s_right_orbit:
    number: upper_playfield-9
  s_red_crystals:
    number: upper_playfield-10
  s_meteor_dust:
    number: upper_playfield-11
  #unused:    
    #number: upper_playfield-12
    #number: upper_playfield-13
    #number: upper_playfield-14
    #number: upper_playfield-15  
