#config_version=6

switches:
  #=============================
  # Cabinet IO Switches
  # - 24 switch inputs, 8 driver outputs
  # - 1 high power driver
  # - 6 low current drivers for LEDs
  # - 2 digital outputs (bill validator and card readers)
  #=============================
  # Cabinet Coin Door
  #-----------------------------
  #unused:
    #number: cabinet-0
    #number: cabinet-1
    #number: cabinet-2
    #number: cabinet-3
    #number: cabinet-4
    #number: cabinet-5
    #number: cabinet-6
    #number: cabinet-7
  #-----------------------------
  # Cabinet IO Left
  #-----------------------------
  s_start:
    number: cabinet-8
  s_lower_left_flipper:
    number: cabinet-9
    debounce: normal
  s_upper_left_flipper:
    number: cabinet-10
    debounce: normal
  s_tilt:
    number: cabinet-11
    debounce: normal
  #unused:
    #number: cabinet-12
    #number: cabinet-13
    #number: cabinet-14
    #number: cabinet-15
  #-----------------------------
  # Cabinet IO Right
  #-----------------------------
  #unused:
    #number: cabinet-16
    #number: cabinet-17
    #number: cabinet-18
    #number: cabinet-19
    #number: cabinet-20
    #number: cabinet-21
    #number: cabinet-22
    #number: cabinet-23
  #-----------------------------
  # Bill/Card/Ticket - UNUSED SHARES PINS W/ Cabinet IO Right
  #-----------------------------
  
  
  #=============================
  # Playfield IO 3208 Switches
  # - 32 switch inputs, 8 driver outputs
  #=============================
  # J8 - Switch Bank 0-7
  #-----------------------------

  s_trough_ball_1: #opto
    number: playfield-0
    type: 'NC'
  s_trough_ball_2:
    number: playfield-1
  s_trough_ball_3:
    number: playfield-2
  s_trough_ball_4:
    number: playfield-3
  s_trough_ball_5:
    number: playfield-4
  s_trough_ball_6:
    number: playfield-5
  s_trough_ball_7:
    number: playfield-6
  s_trough_ball_8:
    number: playfield-7
  #-----------------------------
  # J3 - Switch Bank 8-15
  #-----------------------------
  s_trough_ball_jam: #opto
    number: playfield-8
    type: 'NC'  
  s_sling_left:
    number: playfield-9
  s_sling_right:
    number: playfield-10
  s_lower_left_flipper_eos:
    number: playfield-11
  s_lower_right_flipper_eos:
    number: playfield-12
  s_plunger:
    number: playfield-13
    #number: playfield-14
    #number: playfield-15
  #-----------------------------
    # J6 - Switch Bank 16-23
  #-----------------------------
  #unused:
    #number: playfield-16
    #number: playfield-17
    #number: playfield-18
    #number: playfield-19
    #number: playfield-20
    #number: playfield-21
    #number: playfield-22
    #number: playfield-23
  #-----------------------------
  # J9 - Switch Bank 24-31
  #-----------------------------
  #unused:
    #number: playfield-24
    #number: playfield-25
    #number: playfield-26
    #number: playfield-27
    #number: playfield-28
    #number: playfield-29
    #number: playfield-30
    #number: playfield-31
  
